### ISSUE TITLE
enable OSX on Travis

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#33]
Should we ask Travis to enable OSX builds for vinecopulib?

**Comment by tvatter** [comment]
I removed it a while ago because of weird seg faults that I could not reproduce on my machine (which also runs on OSX). You can notice that uncommenting the OSX part from the build matrix should be enough, but I didn't feel like spending too much time fighting with travis ;) You're welcome to try though...

**Comment by slayoo** [comment]
I've created a pull request with the osx_image override to test if using newer XCode helps:
https://github.com/tvatter/vinecopulib/pull/35
(https://docs.travis-ci.com/user/osx-ci-environment/)

**Comment by slayoo** [comment]
OK - seems to work now!
Please have a look and merge if all OK: https://github.com/tvatter/vinecopulib/pull/35

**Comment by slayoo** [comment]
The PR was merged
