### ISSUE TITLE
what about replacing #ifndex/#define/#endif constructs with #pragma once?

### ISSUE THREAD

**Issue by slayoo** [tvatter/vinecopulib#34]

**Comment by tvatter** [comment]
Why?

If I understand correctly, it is not part of the standard and should not be used if portability is a concern. Furthermore, since the project is rather small, the benefits of using it are limited. 

Note that I didn't know much about it and my sources are:
* [wikipedia article](https://en.wikipedia.org/wiki/Pragma_once)
* [this answer](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard)
* [this one](http://stackoverflow.com/questions/3221968/whats-difference-between-pragma-and-ifndef)
* [this one](http://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards)

**Comment by slayoo** [comment]
- less bug prone (forgotten define name change after using a copy of an old file as a skeleton)
- less code
- all compilers that we might target support it
(but it's of course purely your decision - just wanted to confirm if we go one or the other way)

**Comment by tvatter** [comment]
OK, that's the three advantages that I had understood ;)

I don't like the "non-standard" thing, but I have no strong opinion on this. 

Thomas?

**Comment by tnagler** [comment]
I don't have any opinion on this. The `#ifndef` is certainly more common, at least I've seen this way more often. But if `#pragma once` is the more safe and modern version, we can go with that too.

**Comment by tnagler** [comment]
was addressed by 1727fb1dccf174a8667c757844184a9bc0b88fe9
