### ISSUE TITLE
Refactoring of Vinecop class

### ISSUE THREAD

**Issue by tnagler** [tvatter/vinecopulib#51]
As discussed in #49:
- [x] Change to more natural matrix style (see #48 for the discussion)
- [x] New methods `get_families()`, `get_rotations()` that return the full model matrix.
- [x] Unit tests for structure selection.

**Comment by tvatter** [comment]
Also, I would add:

- Modify `as_vinecop` to avoid starting from the last tree.
- Breaking the loop for truncated vines.

**Comment by tnagler** [comment]
I don't think that this should be a priority now.
- It is only useful in a very specific use case (very high dimension, early truncation).
- Figuring this out probably takes several days. I think we should first clean everything up and release a first version, then we can worry about days.
- The "doing useless stuff" is much less of a problem in C++ where function calls and loops are much faster than in R. To add some numbers to the discussion (`n = 1000, d = 200, familyset = {0, 1, 2, 3, 4, 5, 6}, method = "mle", truncation_level = 5, CMAKE_BUILD_TYPE = Release` ):
          - until truncation: 133.278s
          - after truncation: 9.88442s
          - `as_vinecop`: 10.5193s
The time for `as_vinecop` could actually go up, because we might need to reorder the matrix several times. And we still would need to create all the independence copulas in the pc_store so that the simulation and pdf algorithms work.

**Comment by tvatter** [comment]
- Concerning the specificity of this use case: we'll have to agree to disagree. IMO, you don't need to be in "very" high dimension for truncation to be useful.
- OK, this one is actually a very good argument. I was wondering how hard it would be. If you think that this is hard, then indeed we can wait after the first complete clean-up.
- Oh, I'm really surprised by this results, but alright: it's a very good news. Then a simple improvement will be translate what I implemented for `VineCopula` (i.e., create the tree by dfs in order to avoid moving data around and computing Kendall's tau) , but I agree that this can wait.

**Comment by tnagler** [comment]
all done in #55
